mkdir -p swishy_html
cd swishy_html
curl -L -O https://www.swishy.ai/templates/simple-timelapse
curl -L -O https://www.swishy.ai/templates/typewriter
curl -L -O https://www.swishy.ai/templates/wiggle-text
curl -L -O https://www.swishy.ai/templates/working-on-a-computer
curl -L -O https://www.swishy.ai/templates/particle-explosion
curl -L -O https://www.swishy.ai/templates/image-shuffle-1
curl -L -O https://www.swishy.ai/templates/create
curl -L -O https://www.swishy.ai/templates/bouncing-image
curl -L -O https://www.swishy.ai/templates/premiere-pro-animation
curl -L -O https://www.swishy.ai/templates/newspaper-animation
curl -L -O https://www.swishy.ai/templates/logo-reveal-1
curl -L -O https://www.swishy.ai/templates/github-star-comparison
curl -L -O https://www.swishy.ai/templates/timeline
curl -L -O https://www.swishy.ai/templates/explainer-spheres
curl -L -O https://www.swishy.ai/templates/gravity-thought
curl -L -O https://www.swishy.ai/templates/sticky-notes
curl -L -O https://www.swishy.ai/templates/night-street-market
curl -L -O https://www.swishy.ai/templates/animate-characters
curl -L -O https://www.swishy.ai/templates/retro-phone
curl -L -O https://www.swishy.ai/templates/terminal-showcase
curl -L -O https://www.swishy.ai/templates/generate-ai-voice-animation
curl -L -O https://www.swishy.ai/templates/population
curl -L -O https://www.swishy.ai/templates/outsidelands-poster
curl -L -O https://www.swishy.ai/templates/like
curl -L -O https://www.swishy.ai/templates/loading
curl -L -O https://www.swishy.ai/templates/concert-animation
curl -L -O https://www.swishy.ai/templates/charming-letting
curl -L -O https://www.swishy.ai/templates/simple-chart
curl -L -O https://www.swishy.ai/templates/list-of-things
curl -L -O https://www.swishy.ai/templates/instagram-update-notification-animation
curl -L -O https://www.swishy.ai/templates/a-story-about-the-world
curl -L -O https://www.swishy.ai/templates/photobooth-animation-1
curl -L -O https://www.swishy.ai/templates/scattered-text
curl -L -O https://www.swishy.ai/templates/notepad
curl -L -O https://www.swishy.ai/templates/logo-reveal
curl -L -O https://www.swishy.ai/templates/make-with-notion
curl -L -O https://www.swishy.ai/templates/science-club
curl -L -O https://www.swishy.ai/templates/spill-word
curl -L -O https://www.swishy.ai/templates/ad-spend
curl -L -O https://www.swishy.ai/templates/simulation-terminated
curl -L -O https://www.swishy.ai/templates/folder-gallery-1
curl -L -O https://www.swishy.ai/templates/instagram-profile
curl -L -O https://www.swishy.ai/templates/github-stars-1
curl -L -O https://www.swishy.ai/templates/writing-diary-1
curl -L -O https://www.swishy.ai/templates/pencil-drawing
curl -L -O https://www.swishy.ai/templates/sticky-notes-animation
curl -L -O https://www.swishy.ai/templates/money-falling
curl -L -O https://www.swishy.ai/templates/tech-youtube-1
curl -L -O https://www.swishy.ai/templates/january
curl -L -O https://www.swishy.ai/templates/moneyyyy
