import type React from "react";

export type ControlType = "color" | "text" | "url" | "number" | "boolean" | "font";

export interface Control {
  key: string;
  label: string;
  type: ControlType;
  group: string;
  min?: number;
  max?: number;
  step?: number;
}

export interface CompositionDef {
  id: string;
  title: string;
  description: string;
  color: string;
  icon: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  loadComponent: () => Promise<React.ComponentType<any>>;
  defaultProps: Record<string, unknown>;
  durationInFrames: number;
  fps: number;
  controls: Control[];
}

export const REGISTRY: CompositionDef[] = [
  {
    id: "SpotifyPlayer",
    title: "Spotify Player",
    description: "Vinyl record animation with marquee text and playback controls.",
    color: "#1DB954",
    icon: "🎵",
    loadComponent: () => import("../SpotifyPlayer/Scene").then(m => m.Scene),
    defaultProps: {
      trackTitle: "You've Got The Love (Jamie xx Rework feat. The xx)",
      artistName: "Florence + The Machine, The xx, Jamie xx",
      totalDuration: "5:42",
      vinylLabel: "https://picsum.photos/seed/vinyl/800/800",
      fontFamily: "JetBrains Mono",
      backgroundColor: "#121212",
      textColor: "#FFFFFF",
      secondaryTextColor: "#B3B3B3",
      accentColor: "#1DB954",
      progressBarColor: "#FFFFFF",
      progressTrackColor: "#4D4D4D",
      vinylColor: "#1A1A1A",
      scale: 1,
      animationSpeed: 1,
      rotationSpeed: 0.4,
      marqueeSpeed: 0.8,
      progressDuration: 300,
      showShuffleActive: true,
      showRepeatActive: false,
    },
    durationInFrames: 300,
    fps: 30,
    controls: [
      { key: "trackTitle",    label: "Track Title",              type: "text",    group: "Content" },
      { key: "artistName",    label: "Artist",                   type: "text",    group: "Content" },
      { key: "totalDuration", label: "Duration",                 type: "text",    group: "Content" },
      { key: "vinylLabel",    label: "Vinyl Label (image URL)",  type: "url",     group: "Content" },
      { key: "fontFamily",    label: "Font Family",              type: "font",    group: "Content" },

      { key: "backgroundColor",    label: "Background",     type: "color", group: "Colors" },
      { key: "textColor",          label: "Text",           type: "color", group: "Colors" },
      { key: "secondaryTextColor", label: "Secondary Text", type: "color", group: "Colors" },
      { key: "accentColor",        label: "Accent",         type: "color", group: "Colors" },
      { key: "progressBarColor",   label: "Progress Bar",   type: "color", group: "Colors" },
      { key: "progressTrackColor", label: "Progress Track", type: "color", group: "Colors" },
      { key: "vinylColor",         label: "Vinyl",          type: "color", group: "Colors" },

      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
      { key: "rotationSpeed",    label: "Vinyl Rotation",   type: "number", group: "Animation", min: 0.1, max: 3,   step: 0.1  },
      { key: "marqueeSpeed",     label: "Marquee Speed",    type: "number", group: "Animation", min: 0.3, max: 2,   step: 0.1  },
      { key: "progressDuration", label: "Progress (frames)",type: "number", group: "Animation", min: 60,  max: 500, step: 10   },

      { key: "showShuffleActive", label: "Shuffle Active", type: "boolean", group: "Playback" },
      { key: "showRepeatActive",  label: "Repeat Active",  type: "boolean", group: "Playback" },
    ],
  },
  {
    id: "FutureOfDesign",
    title: "Future of Design",
    description: "Physics-based typography animation with blur and glow effects.",
    color: "#6366f1",
    icon: "✨",
    loadComponent: () => import("../FutureOfDesign/Scene").then(m => m.Scene),
    defaultProps: {
      smallText: "the",
      mainText: "future",
      subText: "of design",
      textColor: "#FFFFFF",
      glowColor: "#FFFFFF",
      backgroundColor: "#0f172a",
      scale: 1.45,
      animationSpeed: 0.6,
      blurAmount: 30,
      slideDistance: 400,
      glowIntensity: 6,
      letterSpacing: -2,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "smallText", label: "Small Text", type: "text", group: "Content" },
      { key: "mainText",  label: "Main Text",  type: "text", group: "Content" },
      { key: "subText",   label: "Sub Text",   type: "text", group: "Content" },

      { key: "backgroundColor", label: "Background", type: "color", group: "Colors" },
      { key: "textColor",       label: "Text",       type: "color", group: "Colors" },
      { key: "glowColor",       label: "Glow",       type: "color", group: "Colors" },

      { key: "scale",         label: "Scale",          type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",label: "Animation Speed",type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
      { key: "blurAmount",    label: "Blur Amount",    type: "number", group: "Animation", min: 0,   max: 50,  step: 5    },
      { key: "slideDistance", label: "Slide Distance", type: "number", group: "Animation", min: 50,  max: 400, step: 25   },
      { key: "glowIntensity", label: "Glow Intensity", type: "number", group: "Animation", min: 0,   max: 10,  step: 1    },
      { key: "letterSpacing", label: "Letter Spacing", type: "number", group: "Animation", min: -20, max: 10,  step: 2    },
    ],
  },
  {
    id: "GoodMood",
    title: "Good Mood",
    description: "Vibrant high-contrast typography with elastic spring-based animations.",
    color: "#ff1d1d",
    icon: "😊",
    loadComponent: () => import("../GoodMood/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 0.9,
      colorO1: "#006eff",
      colorO2: "#ff1d1d",
      colorM: "#ffbd14",
      colorD: "#ff7fa1",
      topRowColor: "#ffffff",
      backgroundColor: "#000000",
      animationSpeed: 0.8,
      stretchIntensity: 0.28,
      fontFamily: "Bebas Neue, Impact, sans-serif",
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.1, max: 2,   step: 0.1  },
      { key: "stretchIntensity", label: "Stretch Intensity",type: "number", group: "Animation", min: 0,   max: 0.5, step: 0.01 },
      
      { key: "topRowColor",    label: "Top Row Color",    type: "color", group: "Colors" },
      { key: "colorO1",        label: "Color O1",         type: "color", group: "Colors" },
      { key: "colorO2",        label: "Color O2",         type: "color", group: "Colors" },
      { key: "colorM",         label: "Color M",          type: "color", group: "Colors" },
      { key: "colorD",         label: "Color D",          type: "color", group: "Colors" },
      { key: "backgroundColor",label: "Background",       type: "color", group: "Colors" },
      
      { key: "fontFamily",     label: "Font Family",      type: "font",  group: "Content" },
    ],
  },
  {
    id: "SwishyMotivational",
    title: "Motivational",
    description: "Multi-scene kinetic typography for motivational stories and insights.",
    color: "#f97316",
    icon: "🔥",
    loadComponent: () => import("../Swishy/Motivational/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
      backgroundColor: "#ffffff",
      textColor: "#111827",
      accentColor: "#3b82f6",
      fontFamily: "Bebas Neue",
      staggerDelay: 10,
    },
    durationInFrames: 340,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
      { key: "backgroundColor",  label: "Background",       type: "color",  group: "Colors" },
      { key: "textColor",        label: "Text",             type: "color",  group: "Colors" },
      { key: "accentColor",      label: "Accent",           type: "color",  group: "Colors" },
      { key: "fontFamily",       label: "Font Family",      type: "font",   group: "Content" },
    ],
  },
  {
    id: "SwishyStorytime",
    title: "Storytime",
    description: "Condensed editorial text sequence with premium typography.",
    color: "#8b5cf6",
    icon: "📖",
    loadComponent: () => import("../Swishy/Storytime/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
      backgroundColor: "#000000",
      textColor: "#ffffff",
      fontFamily: "Playfair Display",
    },
    durationInFrames: 350,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
      { key: "backgroundColor",  label: "Background",       type: "color",  group: "Colors" },
      { key: "textColor",        label: "Text",             type: "color",  group: "Colors" },
      { key: "fontFamily",       label: "Font Family",      type: "font",   group: "Content" },
    ],
  },
  {
    id: "SwishyWorldStory",
    title: "World Story",
    description: "Diverse kinetic typography sequence exploring creation and discovery.",
    color: "#0ea5e9",
    icon: "🌍",
    loadComponent: () => import("../Swishy/AStoryAboutTheWorld/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
      backgroundColor: "#f8fafc",
      textColor: "#1e293b",
      accentColor: "#64748b",
      headingFont: "Playfair Display",
      bodyFont: "DM Sans",
    },
    durationInFrames: 510,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
      { key: "backgroundColor",  label: "Background",       type: "color",  group: "Colors" },
      { key: "textColor",        label: "Text",             type: "color",  group: "Colors" },
      { key: "accentColor",      label: "Accent",           type: "color",  group: "Colors" },
      { key: "headingFont",      label: "Heading Font",     type: "font",   group: "Content" },
      { key: "bodyFont",         label: "Body Font",        type: "font",   group: "Content" },
    ],
  },
  {
    id: "SwishyAnimateCharacters",
    title: "Animate Characters",
    description: "Magical character animations with glowing effects and mystical forests.",
    color: "#a855f7",
    icon: "🦄",
    loadComponent: () => import("../Swishy/AnimateCharacters/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
      backgroundColor: "#0c0a1d",
      accentColor: "#a855f7",
      textColor: "#f8fafc",
    },
    durationInFrames: 300,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
      { key: "backgroundColor",  label: "Background",       type: "color",  group: "Colors" },
      { key: "accentColor",      label: "Accent",           type: "color",  group: "Colors" },
      { key: "textColor",        label: "Text",             type: "color",  group: "Colors" },
    ],
  },
  {
    id: "SwishyN2026",
    title: "2026",
    description: "Swishy template",
    color: "#f13443",
    icon: "🎬",
    loadComponent: () => import("../Swishy/2026/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyN3dCube",
    title: "3d-cube",
    description: "Swishy template",
    color: "#c88f39",
    icon: "🎬",
    loadComponent: () => import("../Swishy/3d-cube/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyAStormOfInfo",
    title: "a-storm-of-info",
    description: "Swishy template",
    color: "#e7abdd",
    icon: "🎬",
    loadComponent: () => import("../Swishy/a-storm-of-info/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyAdSpend",
    title: "ad-spend",
    description: "Swishy template",
    color: "#93c1a4",
    icon: "🎬",
    loadComponent: () => import("../Swishy/ad-spend/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyAlarmToggle1",
    title: "alarm-toggle-1",
    description: "Swishy template",
    color: "#77c6e5",
    icon: "🎬",
    loadComponent: () => import("../Swishy/alarm-toggle-1/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyAnimateNetflixLogo",
    title: "animate-netflix-logo",
    description: "Swishy template",
    color: "#999d61",
    icon: "🎬",
    loadComponent: () => import("../Swishy/animate-netflix-logo/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyAnimatedAppList",
    title: "animated-app-list",
    description: "Swishy template",
    color: "#1b8061",
    icon: "🎬",
    loadComponent: () => import("../Swishy/animated-app-list/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyAnimatedBlob",
    title: "animated-blob",
    description: "Swishy template",
    color: "#4ffc4b",
    icon: "🎬",
    loadComponent: () => import("../Swishy/animated-blob/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyAnimatedEmojiButton",
    title: "animated-emoji-button",
    description: "Swishy template",
    color: "#b88d79",
    icon: "🎬",
    loadComponent: () => import("../Swishy/animated-emoji-button/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyAnimatedYear",
    title: "animated-year",
    description: "Swishy template",
    color: "#573ca7",
    icon: "🎬",
    loadComponent: () => import("../Swishy/animated-year/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyAppAnimation",
    title: "app-animation",
    description: "Swishy template",
    color: "#11dd7c",
    icon: "🎬",
    loadComponent: () => import("../Swishy/app-animation/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyAppVideoShowcase",
    title: "app-video-showcase",
    description: "Swishy template",
    color: "#68d4f1",
    icon: "🎬",
    loadComponent: () => import("../Swishy/app-video-showcase/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyAppleStyle30SecCounter1",
    title: "apple-style-30-sec-counter-1",
    description: "Swishy template",
    color: "#312664",
    icon: "🎬",
    loadComponent: () => import("../Swishy/apple-style-30-sec-counter-1/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyBarChart",
    title: "bar-chart",
    description: "Swishy template",
    color: "#c66ffc",
    icon: "🎬",
    loadComponent: () => import("../Swishy/bar-chart/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyBarChart1",
    title: "bar-chart-1",
    description: "Swishy template",
    color: "#3cd6d3",
    icon: "🎬",
    loadComponent: () => import("../Swishy/bar-chart-1/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyBarChart2",
    title: "bar-chart-2",
    description: "Swishy template",
    color: "#48abb3",
    icon: "🎬",
    loadComponent: () => import("../Swishy/bar-chart-2/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyBouncingImage",
    title: "bouncing-image",
    description: "Swishy template",
    color: "#a1e723",
    icon: "🎬",
    loadComponent: () => import("../Swishy/bouncing-image/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyBranching",
    title: "branching",
    description: "Swishy template",
    color: "#ea29e9",
    icon: "🎬",
    loadComponent: () => import("../Swishy/branching/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyBrandSpinning",
    title: "brand-spinning",
    description: "Swishy template",
    color: "#206538",
    icon: "🎬",
    loadComponent: () => import("../Swishy/brand-spinning/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyCalendarGridDrop",
    title: "calendar-grid-drop",
    description: "Swishy template",
    color: "#b11f4d",
    icon: "🎬",
    loadComponent: () => import("../Swishy/calendar-grid-drop/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyCarCrashStory",
    title: "car-crash-story",
    description: "Swishy template",
    color: "#a6f125",
    icon: "🎬",
    loadComponent: () => import("../Swishy/car-crash-story/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyCarRacing",
    title: "car-racing",
    description: "Swishy template",
    color: "#7ac827",
    icon: "🎬",
    loadComponent: () => import("../Swishy/car-racing/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyCard",
    title: "card",
    description: "Swishy template",
    color: "#85269b",
    icon: "🎬",
    loadComponent: () => import("../Swishy/card/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyCharmingLetting",
    title: "charming-letting",
    description: "Swishy template",
    color: "#fca01b",
    icon: "🎬",
    loadComponent: () => import("../Swishy/charming-letting/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyChartWith",
    title: "chart-with",
    description: "Swishy template",
    color: "#5e9bc4",
    icon: "🎬",
    loadComponent: () => import("../Swishy/chart-with/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyClickAnimation",
    title: "click-animation",
    description: "Swishy template",
    color: "#410e6b",
    icon: "🎬",
    loadComponent: () => import("../Swishy/click-animation/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyClockAndText",
    title: "clock-and-text",
    description: "Swishy template",
    color: "#7bc3b5",
    icon: "🎬",
    loadComponent: () => import("../Swishy/clock-and-text/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyComicStyle",
    title: "comic-style",
    description: "Swishy template",
    color: "#f98bd3",
    icon: "🎬",
    loadComponent: () => import("../Swishy/comic-style/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyConcertAnimation",
    title: "concert-animation",
    description: "Swishy template",
    color: "#967521",
    icon: "🎬",
    loadComponent: () => import("../Swishy/concert-animation/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyCopyAndPaste",
    title: "copy-and-paste",
    description: "Swishy template",
    color: "#ae7980",
    icon: "🎬",
    loadComponent: () => import("../Swishy/copy-and-paste/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyCreate",
    title: "create",
    description: "Swishy template",
    color: "#cf16cd",
    icon: "🎬",
    loadComponent: () => import("../Swishy/create/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyEnergyText",
    title: "energy-text",
    description: "Swishy template",
    color: "#cf1361",
    icon: "🎬",
    loadComponent: () => import("../Swishy/energy-text/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyErrorError",
    title: "error-error",
    description: "Swishy template",
    color: "#de8cbb",
    icon: "🎬",
    loadComponent: () => import("../Swishy/error-error/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyExplainerSpheres",
    title: "explainer-spheres",
    description: "Swishy template",
    color: "#94c6a2",
    icon: "🎬",
    loadComponent: () => import("../Swishy/explainer-spheres/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyExtend",
    title: "extend",
    description: "Swishy template",
    color: "#fe60a1",
    icon: "🎬",
    loadComponent: () => import("../Swishy/extend/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyFinancials",
    title: "financials",
    description: "Swishy template",
    color: "#9412f5",
    icon: "🎬",
    loadComponent: () => import("../Swishy/financials/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyFintechDashboard",
    title: "fintech-dashboard",
    description: "Swishy template",
    color: "#5a7c52",
    icon: "🎬",
    loadComponent: () => import("../Swishy/fintech-dashboard/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyFlightProgress",
    title: "flight-progress",
    description: "Swishy template",
    color: "#02c9b6",
    icon: "🎬",
    loadComponent: () => import("../Swishy/flight-progress/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyFlightsAnimation",
    title: "flights-animation",
    description: "Swishy template",
    color: "#41db23",
    icon: "🎬",
    loadComponent: () => import("../Swishy/flights-animation/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyFolderGallery1",
    title: "folder-gallery-1",
    description: "Swishy template",
    color: "#0b7d1f",
    icon: "🎬",
    loadComponent: () => import("../Swishy/folder-gallery-1/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyFriendshipBeads1",
    title: "friendship-beads-1",
    description: "Swishy template",
    color: "#ac6dc1",
    icon: "🎬",
    loadComponent: () => import("../Swishy/friendship-beads-1/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyFunnelTextAnimation",
    title: "funnel-text-animation",
    description: "Swishy template",
    color: "#ef48f2",
    icon: "🎬",
    loadComponent: () => import("../Swishy/funnel-text-animation/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyGenerateAiVoiceAnimation",
    title: "generate-ai-voice-animation",
    description: "Swishy template",
    color: "#9cd8f4",
    icon: "🎬",
    loadComponent: () => import("../Swishy/generate-ai-voice-animation/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyGithubStarComparison",
    title: "github-star-comparison",
    description: "Swishy template",
    color: "#a44c49",
    icon: "🎬",
    loadComponent: () => import("../Swishy/github-star-comparison/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyGithubStars1",
    title: "github-stars-1",
    description: "Swishy template",
    color: "#58344f",
    icon: "🎬",
    loadComponent: () => import("../Swishy/github-stars-1/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyGoals",
    title: "goals",
    description: "Swishy template",
    color: "#b42946",
    icon: "🎬",
    loadComponent: () => import("../Swishy/goals/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyGravityThought",
    title: "gravity-thought",
    description: "Swishy template",
    color: "#067f59",
    icon: "🎬",
    loadComponent: () => import("../Swishy/gravity-thought/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyHeartCrushButton",
    title: "heart-crush-button",
    description: "Swishy template",
    color: "#4265ff",
    icon: "🎬",
    loadComponent: () => import("../Swishy/heart-crush-button/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyIWantASmoothAnimationWhereTheTextWith2Li",
    title: "i-want-a-smooth-animation-where-the-text-with-2-li",
    description: "Swishy template",
    color: "#1162a8",
    icon: "🎬",
    loadComponent: () => import("../Swishy/i-want-a-smooth-animation-where-the-text-with-2-li/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyImageShuffle1",
    title: "image-shuffle-1",
    description: "Swishy template",
    color: "#0db218",
    icon: "🎬",
    loadComponent: () => import("../Swishy/image-shuffle-1/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyInstagramLogoAnimation",
    title: "instagram-logo-animation",
    description: "Swishy template",
    color: "#5c3291",
    icon: "🎬",
    loadComponent: () => import("../Swishy/instagram-logo-animation/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyInstagramProfile",
    title: "instagram-profile",
    description: "Swishy template",
    color: "#62e1c5",
    icon: "🎬",
    loadComponent: () => import("../Swishy/instagram-profile/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyInstagramStories",
    title: "instagram-stories",
    description: "Swishy template",
    color: "#b581b6",
    icon: "🎬",
    loadComponent: () => import("../Swishy/instagram-stories/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyInstagramStory3Images",
    title: "instagram-story-3-images",
    description: "Swishy template",
    color: "#dd8107",
    icon: "🎬",
    loadComponent: () => import("../Swishy/instagram-story-3-images/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyInstagramUpdateNotificationAnimation",
    title: "instagram-update-notification-animation",
    description: "Swishy template",
    color: "#3cb2d7",
    icon: "🎬",
    loadComponent: () => import("../Swishy/instagram-update-notification-animation/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyInteractivePixelArtWaves",
    title: "interactive-pixel-art-waves",
    description: "Swishy template",
    color: "#e96a83",
    icon: "🎬",
    loadComponent: () => import("../Swishy/interactive-pixel-art-waves/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyIosNotification",
    title: "ios-notification",
    description: "Swishy template",
    color: "#1bbdaa",
    icon: "🎬",
    loadComponent: () => import("../Swishy/ios-notification/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyJanuary",
    title: "january",
    description: "Swishy template",
    color: "#322c6d",
    icon: "🎬",
    loadComponent: () => import("../Swishy/january/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyJune",
    title: "june",
    description: "Swishy template",
    color: "#2296ca",
    icon: "🎬",
    loadComponent: () => import("../Swishy/june/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyLifeLineAnimation",
    title: "life-line-animation",
    description: "Swishy template",
    color: "#1d29f2",
    icon: "🎬",
    loadComponent: () => import("../Swishy/life-line-animation/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyLike",
    title: "like",
    description: "Swishy template",
    color: "#63b759",
    icon: "🎬",
    loadComponent: () => import("../Swishy/like/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyListOfThings",
    title: "list-of-things",
    description: "Swishy template",
    color: "#f2a4ae",
    icon: "🎬",
    loadComponent: () => import("../Swishy/list-of-things/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyLoading",
    title: "loading",
    description: "Swishy template",
    color: "#697e21",
    icon: "🎬",
    loadComponent: () => import("../Swishy/loading/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyLocationPopUp",
    title: "location-pop-up",
    description: "Swishy template",
    color: "#e2de0a",
    icon: "🎬",
    loadComponent: () => import("../Swishy/location-pop-up/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyLogoCode",
    title: "logo-code",
    description: "Swishy template",
    color: "#2d790a",
    icon: "🎬",
    loadComponent: () => import("../Swishy/logo-code/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyLogoReveal1",
    title: "logo-reveal-1",
    description: "Swishy template",
    color: "#b8a975",
    icon: "🎬",
    loadComponent: () => import("../Swishy/logo-reveal-1/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyLogoSpin",
    title: "logo-spin",
    description: "Swishy template",
    color: "#4179d7",
    icon: "🎬",
    loadComponent: () => import("../Swishy/logo-spin/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyMakeWithNotion",
    title: "make-with-notion",
    description: "Swishy template",
    color: "#623efa",
    icon: "🎬",
    loadComponent: () => import("../Swishy/make-with-notion/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyMakinBank",
    title: "makin-bank",
    description: "Swishy template",
    color: "#825156",
    icon: "🎬",
    loadComponent: () => import("../Swishy/makin-bank/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyMap",
    title: "map",
    description: "Swishy template",
    color: "#e088d4",
    icon: "🎬",
    loadComponent: () => import("../Swishy/map/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyMarioGame",
    title: "mario-game",
    description: "Swishy template",
    color: "#dae3ac",
    icon: "🎬",
    loadComponent: () => import("../Swishy/mario-game/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyMobileBookshelf",
    title: "mobile-bookshelf",
    description: "Swishy template",
    color: "#613933",
    icon: "🎬",
    loadComponent: () => import("../Swishy/mobile-bookshelf/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyMoneyFalling",
    title: "money-falling",
    description: "Swishy template",
    color: "#237c24",
    icon: "🎬",
    loadComponent: () => import("../Swishy/money-falling/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyMoneyyyy",
    title: "moneyyyy",
    description: "Swishy template",
    color: "#03abf0",
    icon: "🎬",
    loadComponent: () => import("../Swishy/moneyyyy/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyMorphBlocks",
    title: "morph-blocks",
    description: "Swishy template",
    color: "#22ccb4",
    icon: "🎬",
    loadComponent: () => import("../Swishy/morph-blocks/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyNavalQuote",
    title: "naval-quote",
    description: "Swishy template",
    color: "#636db2",
    icon: "🎬",
    loadComponent: () => import("../Swishy/naval-quote/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyNewspaperAnimation",
    title: "newspaper-animation",
    description: "Swishy template",
    color: "#0428e7",
    icon: "🎬",
    loadComponent: () => import("../Swishy/newspaper-animation/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyNightStreetMarket",
    title: "night-street-market",
    description: "Swishy template",
    color: "#d5d146",
    icon: "🎬",
    loadComponent: () => import("../Swishy/night-street-market/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyNotepad",
    title: "notepad",
    description: "Swishy template",
    color: "#e4f6ac",
    icon: "🎬",
    loadComponent: () => import("../Swishy/notepad/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyNotionAnimatedHub",
    title: "notion-animated-hub",
    description: "Swishy template",
    color: "#ed1976",
    icon: "🎬",
    loadComponent: () => import("../Swishy/notion-animated-hub/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyOnOffToggle",
    title: "on-off-toggle",
    description: "Swishy template",
    color: "#c233f9",
    icon: "🎬",
    loadComponent: () => import("../Swishy/on-off-toggle/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyOutsidelandsPoster",
    title: "outsidelands-poster",
    description: "Swishy template",
    color: "#622c2f",
    icon: "🎬",
    loadComponent: () => import("../Swishy/outsidelands-poster/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyParticleExplosion",
    title: "particle-explosion",
    description: "Swishy template",
    color: "#c30869",
    icon: "🎬",
    loadComponent: () => import("../Swishy/particle-explosion/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyPhoneMessages",
    title: "phone-messages",
    description: "Swishy template",
    color: "#5b2284",
    icon: "🎬",
    loadComponent: () => import("../Swishy/phone-messages/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyPhoneMessages1",
    title: "phone-messages-1",
    description: "Swishy template",
    color: "#18f2fa",
    icon: "🎬",
    loadComponent: () => import("../Swishy/phone-messages-1/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyPhoneNotificationPopUp",
    title: "phone-notification-pop-up",
    description: "Swishy template",
    color: "#899ac0",
    icon: "🎬",
    loadComponent: () => import("../Swishy/phone-notification-pop-up/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyPhotoboothAnimation1",
    title: "photobooth-animation-1",
    description: "Swishy template",
    color: "#6e2811",
    icon: "🎬",
    loadComponent: () => import("../Swishy/photobooth-animation-1/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyPhotosAnimation",
    title: "photos-animation",
    description: "Swishy template",
    color: "#e5167c",
    icon: "🎬",
    loadComponent: () => import("../Swishy/photos-animation/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyPhotoshopAnimation1",
    title: "photoshop-animation-1",
    description: "Swishy template",
    color: "#706690",
    icon: "🎬",
    loadComponent: () => import("../Swishy/photoshop-animation-1/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyPins",
    title: "pins",
    description: "Swishy template",
    color: "#c5412a",
    icon: "🎬",
    loadComponent: () => import("../Swishy/pins/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyPopUpMessageBubble",
    title: "pop-up-message-bubble",
    description: "Swishy template",
    color: "#4e2173",
    icon: "🎬",
    loadComponent: () => import("../Swishy/pop-up-message-bubble/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyPopulation",
    title: "population",
    description: "Swishy template",
    color: "#e28dc0",
    icon: "🎬",
    loadComponent: () => import("../Swishy/population/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyPremiereProAnimation",
    title: "premiere-pro-animation",
    description: "Swishy template",
    color: "#da3d8b",
    icon: "🎬",
    loadComponent: () => import("../Swishy/premiere-pro-animation/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyRetroPhone",
    title: "retro-phone",
    description: "Swishy template",
    color: "#d10c0f",
    icon: "🎬",
    loadComponent: () => import("../Swishy/retro-phone/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishySaasSecurity",
    title: "saas-security",
    description: "Swishy template",
    color: "#80ae91",
    icon: "🎬",
    loadComponent: () => import("../Swishy/saas-security/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyScatteredText",
    title: "scattered-text",
    description: "Swishy template",
    color: "#383bcc",
    icon: "🎬",
    loadComponent: () => import("../Swishy/scattered-text/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyScienceClub",
    title: "science-club",
    description: "Swishy template",
    color: "#0e9830",
    icon: "🎬",
    loadComponent: () => import("../Swishy/science-club/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishySearchBox",
    title: "search-box",
    description: "Swishy template",
    color: "#635bf6",
    icon: "🎬",
    loadComponent: () => import("../Swishy/search-box/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishySentenceReveal",
    title: "sentence-reveal",
    description: "Swishy template",
    color: "#664393",
    icon: "🎬",
    loadComponent: () => import("../Swishy/sentence-reveal/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishySimpleChart",
    title: "simple-chart",
    description: "Swishy template",
    color: "#d4d7cd",
    icon: "🎬",
    loadComponent: () => import("../Swishy/simple-chart/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishySimpleTimelapse",
    title: "simple-timelapse",
    description: "Swishy template",
    color: "#eec07f",
    icon: "🎬",
    loadComponent: () => import("../Swishy/simple-timelapse/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishySimpleTimelapse2",
    title: "simple-timelapse-2",
    description: "Swishy template",
    color: "#34d8cb",
    icon: "🎬",
    loadComponent: () => import("../Swishy/simple-timelapse-2/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishySimulationTerminated",
    title: "simulation-terminated",
    description: "Swishy template",
    color: "#0fc531",
    icon: "🎬",
    loadComponent: () => import("../Swishy/simulation-terminated/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishySpillWord",
    title: "spill-word",
    description: "Swishy template",
    color: "#2b29bd",
    icon: "🎬",
    loadComponent: () => import("../Swishy/spill-word/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishySpinningVinylPlayer1",
    title: "spinning-vinyl-player-1",
    description: "Swishy template",
    color: "#23052b",
    icon: "🎬",
    loadComponent: () => import("../Swishy/spinning-vinyl-player-1/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishySpotifyPlayerAnimation1",
    title: "spotify-player-animation-1",
    description: "Swishy template",
    color: "#f08fc0",
    icon: "🎬",
    loadComponent: () => import("../Swishy/spotify-player-animation-1/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyStickyNotes",
    title: "sticky-notes",
    description: "Swishy template",
    color: "#8f7997",
    icon: "🎬",
    loadComponent: () => import("../Swishy/sticky-notes/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyStickyNotesAnimation",
    title: "sticky-notes-animation",
    description: "Swishy template",
    color: "#188faa",
    icon: "🎬",
    loadComponent: () => import("../Swishy/sticky-notes-animation/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishySystem",
    title: "system",
    description: "Swishy template",
    color: "#5af5f0",
    icon: "🎬",
    loadComponent: () => import("../Swishy/system/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyTechYoutube1",
    title: "tech-youtube-1",
    description: "Swishy template",
    color: "#c934e7",
    icon: "🎬",
    loadComponent: () => import("../Swishy/tech-youtube-1/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyTerminalShowcase",
    title: "terminal-showcase",
    description: "Swishy template",
    color: "#6547e0",
    icon: "🎬",
    loadComponent: () => import("../Swishy/terminal-showcase/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyTerminalTyping",
    title: "terminal-typing",
    description: "Swishy template",
    color: "#45f0f0",
    icon: "🎬",
    loadComponent: () => import("../Swishy/terminal-typing/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyTextIntro",
    title: "text-intro",
    description: "Swishy template",
    color: "#0c850f",
    icon: "🎬",
    loadComponent: () => import("../Swishy/text-intro/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyTheFutureOfDesign1",
    title: "the-future-of-design-1",
    description: "Swishy template",
    color: "#91fe33",
    icon: "🎬",
    loadComponent: () => import("../Swishy/the-future-of-design-1/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyThinking",
    title: "thinking",
    description: "Swishy template",
    color: "#df399e",
    icon: "🎬",
    loadComponent: () => import("../Swishy/thinking/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyTimeline",
    title: "timeline",
    description: "Swishy template",
    color: "#a4a2af",
    icon: "🎬",
    loadComponent: () => import("../Swishy/timeline/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyTypewriter",
    title: "typewriter",
    description: "Swishy template",
    color: "#7adaff",
    icon: "🎬",
    loadComponent: () => import("../Swishy/typewriter/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyTypingEffect",
    title: "typing-effect",
    description: "Swishy template",
    color: "#18f983",
    icon: "🎬",
    loadComponent: () => import("../Swishy/typing-effect/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyUpworkAd",
    title: "upwork-ad",
    description: "Swishy template",
    color: "#ff60af",
    icon: "🎬",
    loadComponent: () => import("../Swishy/upwork-ad/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyViewCartAnimation1",
    title: "view-cart-animation-1",
    description: "Swishy template",
    color: "#277000",
    icon: "🎬",
    loadComponent: () => import("../Swishy/view-cart-animation-1/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyWebsiteReveal",
    title: "website-reveal",
    description: "Swishy template",
    color: "#beccf6",
    icon: "🎬",
    loadComponent: () => import("../Swishy/website-reveal/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyWeddingAnnouncement",
    title: "wedding-announcement",
    description: "Swishy template",
    color: "#4e1c7d",
    icon: "🎬",
    loadComponent: () => import("../Swishy/wedding-announcement/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyWellnessAppMoods",
    title: "wellness-app-moods",
    description: "Swishy template",
    color: "#c7389c",
    icon: "🎬",
    loadComponent: () => import("../Swishy/wellness-app-moods/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyWhatsappConvo",
    title: "whatsapp-convo",
    description: "Swishy template",
    color: "#35a7da",
    icon: "🎬",
    loadComponent: () => import("../Swishy/whatsapp-convo/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyWiggleText",
    title: "wiggle-text",
    description: "Swishy template",
    color: "#35dfa1",
    icon: "🎬",
    loadComponent: () => import("../Swishy/wiggle-text/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyWindows98Style",
    title: "windows-98-style",
    description: "Swishy template",
    color: "#68be42",
    icon: "🎬",
    loadComponent: () => import("../Swishy/windows-98-style/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyWinsVsLosses",
    title: "wins-vs-losses",
    description: "Swishy template",
    color: "#830a74",
    icon: "🎬",
    loadComponent: () => import("../Swishy/wins-vs-losses/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyWorkingOnAComputer",
    title: "working-on-a-computer",
    description: "Swishy template",
    color: "#2982e2",
    icon: "🎬",
    loadComponent: () => import("../Swishy/working-on-a-computer/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyWritingDiary1",
    title: "writing-diary-1",
    description: "Swishy template",
    color: "#627879",
    icon: "🎬",
    loadComponent: () => import("../Swishy/writing-diary-1/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyYearsRollingText",
    title: "years-rolling-text",
    description: "Swishy template",
    color: "#36a003",
    icon: "🎬",
    loadComponent: () => import("../Swishy/years-rolling-text/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
  {
    id: "SwishyYoutubeSubscribeButton",
    title: "youtube-subscribe-button",
    description: "Swishy template",
    color: "#9fc038",
    icon: "🎬",
    loadComponent: () => import("../Swishy/youtube-subscribe-button/Scene").then(m => m.Scene),
    defaultProps: {
      scale: 1,
      animationSpeed: 1,
    },
    durationInFrames: 150,
    fps: 30,
    controls: [
      { key: "scale",            label: "Scale",            type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.05 },
      { key: "animationSpeed",   label: "Animation Speed",  type: "number", group: "Animation", min: 0.5, max: 2,   step: 0.1  },
    ],
  },
];
